---
services:
    openwebui:
        restart: unless-stopped
        image: ghcr.io/open-webui/open-webui:main@sha256:0010ced098045adebf55850a579f741b4827f0405bb7ef0718345988f5547151
        ports:
            - 3006:8080
        volumes:
            - /opt/open-webui/data:/app/backend/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.open-webui.rule=Host(`open-webui.internal.mikeage.net`)
