---
services:
    openwebui:
        restart: unless-stopped
        image: ghcr.io/open-webui/open-webui:main@sha256:8afd2d774834c618a75411b3491cdc5da7396dc464f56a160b937ff2992eb6e4
        ports:
            - 3006:8080
        volumes:
            - /opt/open-webui/data:/app/backend/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.open-webui.rule=Host(`open-webui.internal.mikeage.net`)
