---
services:
    openwebui:
        restart: unless-stopped
        image: ghcr.io/open-webui/open-webui:main@sha256:a26effeb220e132482bf7e0560b3404843e7bc40d23051144e062960df8df6b0
        ports:
            - 3006:8080
        volumes:
            - /opt/open-webui/data:/app/backend/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.open-webui.rule=Host(`open-webui.internal.mikeage.net`)
