---
services:
    a1mini:
        restart: unless-stopped
        image: octoeverywhere/octoeverywhere:4.6.8@sha256:3b3480d9f3520cde8ddaa0b7addb9714c44e6e82f0ec26fc467d9a4e4df9f379
        environment:
            - ACCESS_CODE=39994545
            - SERIAL_NUMBER=0309DA462001807
            - PRINTER_IP=a1mini.lan
            - TZ=Asia/Jerusalem
        volumes:
            - /opt/octoeverywhere/a1mini:/data
