---
services:
    a1mini:
        restart: unless-stopped
        image: octoeverywhere/octoeverywhere:5.2.0@sha256:4306f335a35bc1d6f2474c3459660c0e758d51e0f2a3db736ebcc8b6c910ed56
        environment:
            - ACCESS_CODE=39994545
            - SERIAL_NUMBER=0309DA462001807
            - PRINTER_IP=a1mini.lan
            - TZ=Asia/Jerusalem
        volumes:
            - /opt/octoeverywhere/a1mini:/data
        healthcheck:
            test: [CMD-SHELL, test -w /data && test -d /data/octoeverywhere-store && test -d /data/logs]
            start_period: 30s
            interval: 30s
            timeout: 5s
            retries: 3
