---
repos:
    - repo: local
      hooks:
          - id: check-sops-env
            name: Ensure env files are sops encrypted
            entry: bash scripts/check_sops_env.sh
            language: system
            files: (^|/)[^/]+\.env$
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-json
            files: ^renovate\.json$
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
