---
services:
    dococd:
        image: ghcr.io/kimdre/doco-cd:0.101.0@sha256:21bbf705ebe1cbc21afbca6f9af777d61dfe54549e40000d0533be7d8c4beafe
        restart: unless-stopped
        depends_on:
            - apprise
        ports:
            - 127.0.0.1:8070:80
        environment:
            TZ: ${TZ}
            LOG_LEVEL: ${LOG_LEVEL}
            API_SECRET_FILE: /run/secrets/api_secret
            POLL_CONFIG: |
                - url: ${REPO_URL}
                  reference: ${REPO_REFERENCE}
                  interval: ${POLL_INTERVAL}
                  target: ${DOCO_TARGET}
            SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
            SSH_PRIVATE_KEY_FILE: /run/secrets/ssh_private_key
            APPRISE_API_URL: http://apprise:8000/notify
            APPRISE_NOTIFY_LEVEL: ${APPRISE_NOTIFY_LEVEL}
            APPRISE_NOTIFY_URLS_FILE: /run/secrets/apprise_notify_urls
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/doco-cd/data:/data
        secrets:
            - api_secret
            - apprise_notify_urls
            - sops_age_key
            - ssh_private_key
        cap_drop:
            - ALL
        healthcheck:
            test: [CMD, /doco-cd, healthcheck]
            start_period: 15s
            interval: 30s
            timeout: 5s
            retries: 3

    apprise:
        image: caronc/apprise:latest@sha256:91321755496e8472bdb674e4b14eb64d1f3b15510ef94971309c9f76ef3171e7
        restart: unless-stopped
        environment:
            TZ: ${TZ}
            APPRISE_WORKER_COUNT: 1
        volumes:
            - apprise-config:/config
            - apprise-plugin:/plugin
            - apprise-attach:/attach
        healthcheck:
            test: [CMD, python3, -c, "import urllib.request; urllib.request.urlopen('http://localhost:8000/status', timeout=4).close()"]
            start_period: 15s
            interval: 30s
            timeout: 5s
            retries: 3

secrets:
    api_secret:
        file: /opt/doco-cd/secrets/api_secret
    apprise_notify_urls:
        file: /opt/doco-cd/secrets/apprise_notify_urls
    sops_age_key:
        file: /opt/doco-cd/secrets/sops_age_key.txt
    ssh_private_key:
        file: /opt/doco-cd/secrets/id_ed25519_doco
volumes:
    apprise-config:
    apprise-plugin:
    apprise-attach:
