---
services:
    db:
        image: postgres:18.3@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
        restart: unless-stopped
        shm_size: 128mb
        volumes:
            - /opt/dasharr/db:/var/lib/postgresql/
        env_file:
            - .env
        healthcheck:
            test: [CMD-SHELL, pg_isready -U dasharr]
            interval: 5s
            timeout: 5s
            retries: 5

    dasharr:
        image: ghcr.io/arcadia-solutions/dasharr:latest@sha256:5503eebcfed469e2d20d6a4875ceee53bb2564841d68d23b515cae6bc51f6b27
        restart: unless-stopped
        ports:
            - 3002:80
        environment:
            - ENV=Docker
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        labels:
            - traefik.enable=true
            - traefik.http.routers.dasharr.rule=Host(`dasharr.internal.mikeage.net`)
