---
services:
    vaultwarden:
        image: vaultwarden/server:latest@sha256:9a8eec71f4a52411cc43edc7a50f33e9b6f62b5baca0dd95f0c6e7fd60f1a341
        restart: unless-stopped
        environment:
            DOMAIN: https://vaultwarden.internal.mikeage.net
            SIGNUPS_ALLOWED: 'false'
            ADMIN_TOKEN: ${ADMIN_TOKEN}
            SMTP_HOST: outbound.mikeage.net
            SMTP_FROM: vaultwarden@mikeage.net
            SMTP_PORT: 2525
            SMTP_SECURITY: starttls
            SMTP_USERNAME: ${EMAIL_USER}
            SMTP_PASSWORD: ${EMAIL_PASSWORD}
            TZ: Asia/Jerusalem
        volumes:
            - /opt/vaultwarden/data:/data
        ports:
            - 11001:80
        labels:
            - traefik.enable=true
            - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.internal.mikeage.net`)
