---
services:
    vaultwarden:
        image: vaultwarden/server:1.35.8@sha256:c4f6056fe0c288a052a223cecd263a90d1dda1a0177bb5b054a363a6c7b211d9
        restart: unless-stopped
        environment:
            DOMAIN: https://vaultwarden.internal.mikeage.net
            SIGNUPS_ALLOWED: 'false'
            ADMIN_TOKEN: ${ADMIN_TOKEN}
            SMTP_HOST: outbound.mikeage.net
            SMTP_FROM: vaultwarden@mikeage.net
            SMTP_PORT: 2525
            SMTP_SECURITY: starttls
            SMTP_USERNAME: ${EMAIL_USER}
            SMTP_PASSWORD: ${EMAIL_PASSWORD}
            TZ: Asia/Jerusalem
        volumes:
            - /opt/vaultwarden/data:/data
        ports:
            - 11001:80
        labels:
            - traefik.enable=true
            - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.internal.mikeage.net`)
