---
services:
    bentopdf:
        image: ghcr.io/alam00000/bentopdf-simple:2.8.8@sha256:3d62b8f8eece5fe947026ac3925ff08fda245b3d6ba2c3916b94da91e0010c74 # Recommended
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:8080/]
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        ports:
            - 3007:8080
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.bentopdf.rule=Host(`bentopdf.internal.mikeage.net`)
