---
services:
    bentopdf:
        image: ghcr.io/alam00000/bentopdf-simple:2.8.2@sha256:d59a3812cb98c4887672ea73425722ee3dd7010969736c974c6b4ce7ba32c4fb # Recommended
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:8080/]
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        ports:
            - 3007:8080
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.bentopdf.rule=Host(`bentopdf.internal.mikeage.net`)
