---
services:
    rsyslog-dockerlogs:
        image: rsyslog/rsyslog-dockerlogs:latest@sha256:b22e575e7d553c05119d7c7493fdf4ef30e4602dff9bf5e5a87f3ee6724df003
        restart: unless-stopped
        environment:
            REMOTE_SERVER_NAME: logcollector.lan # your collector
            REMOTE_SERVER_PORT: '514'
            RSYSLOG_HOSTNAME: ${HOSTNAME}    # or hardcode
      # Optional: include stderr too (enabled by default); add filters via labels later
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
