---
services:
    tailscale-router:
        image: tailscale/tailscale:v1.98.10@sha256:cdf5612ded5be1344f1a704b8c5e53496db97376bb533e5e15f141e48bf60cc0
        hostname: ${TS_HOSTNAME:?set TS_HOSTNAME}
        network_mode: host
        restart: unless-stopped
        healthcheck:
            test: [CMD, tailscale, status]
            start_period: 20s
            interval: 30s
            timeout: 10s
            retries: 5
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        volumes:
            - /dev/net/tun:/dev/net/tun
            - /opt/tailscale/data:/var/lib/tailscale
        environment:
            - TS_EXTRA_ARGS=--login-server https://headscale.mikeage.net --accept-dns=true --advertise-exit-node --advertise-routes=192.168.0.0/16
            - TS_STATE_DIR=/var/lib/tailscale
            - TZ=Asia/Jerusalem
            - TS_HOSTNAME=${TS_HOSTNAME:?set TS_HOSTNAME}
