---
services:
    mysql:
        image: mariadb:lts
        command: --transaction-isolation=READ-COMMITTED
        restart: unless-stopped
        healthcheck:
            test: [CMD-SHELL, mariadb-admin ping -h 127.0.0.1 -u"$$MYSQL_USER" -p"$$MYSQL_PASSWORD" --silent]
            start_period: 20s
            interval: 10s
            timeout: 5s
            retries: 6
        volumes:
            - /opt/nextcloud/db:/var/lib/mysql
        environment:
            - MARIADB_AUTO_UPGRADE=1
            - MARIADB_DISABLE_UPGRADE_BACKUP=1
            - TZ=Asia/Jerusalem
        env_file:
            - db.env
    redis:
        image: redis:alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17
        restart: unless-stopped
        healthcheck:
            test: [CMD, redis-cli, ping]
            start_period: 5s
            interval: 10s
            timeout: 5s
            retries: 5
    #command: redis-server --requirepass nextcloud_redis_pass
        volumes:
            - redis_data:/data
    nextcloud:
        build: ./fpm
        restart: unless-stopped
        healthcheck:
            test: [CMD, php, -r, '$$s=@fsockopen("127.0.0.1", 9000); if ($$s) { fclose($$s); exit(0); } exit(1);']
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        volumes:
            - /opt/nextcloud/main_html:/var/www/html
            - nextcloud_data:/var/www/html/data
            # - pictures:/var/www/html/data/mikeage/files/Photos:ro
            - type: tmpfs
              target: /tmp:exec
        environment:
            - MYSQL_HOST=mysql
            - REDIS_HOST=redis
            - TZ=Asia/Jerusalem
        env_file:
            - db.env
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
    web:
        image: nginx:alpine-slim@sha256:c9366b8c560169b101ca0e5422ed063b20779e6454c2326b9c9704225c9b0c08
        restart: unless-stopped
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1/status.php]
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        environment:
            - TZ=Asia/Jerusalem
        ports:
            - 5080:80
        volumes:
            - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
            - /opt/nextcloud/main_html:/var/www/html:ro
            - nextcloud_data:/var/www/html/data:ro
            # - pictures:/var/www/html/data/mikeage/files/Photos:ro
        depends_on:
            nextcloud:
                condition: service_healthy
    # go-vod:
    #     image: radialapps/go-vod
    #     init: true
    #     restart: unless-stopped
    #     depends_on:
    #         - nextcloud
    #         - web
    #     environment:
    #         - NEXTCLOUD_HOST=http://web
    #         - NEXTCLOUD_ALLOW_INSECURE=1
    #         - TZ=Asia/Jerusalem
    #     devices:
    #   #- /dev/dri:/dev/dri
    #         - /dev/dri/card1:/dev/dri/card0
    #         - /dev/dri/renderD128:/dev/dri/renderD128
    #     volumes:
    #         - /opt/nextcloud/main_html:/var/www/html:ro
    #         - nextcloud_data:/var/www/html/data:ro
    #         - pictures:/var/www/html/data/mikeage/files/Photos:ro
volumes:
    redis_data:
    nextcloud_data:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/storage/permanent/nextcloud_data
    # pictures:
    #     driver: local
    #     driver_opts:
    #         type: nfs
    #         o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
    #         device: :/storage/permanent/pictures
