---
services:
    radarr:
        image: lscr.io/linuxserver/radarr:latest@sha256:6f1dda18354ea7f28cead8f6d099fc8222498c3ae165f567d504ed04d70980d7
        healthcheck:
            test: [CMD-SHELL, "bash -ec 'exec 3<>/dev/tcp/127.0.0.1/7878; printf \"GET / HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\\
                      n\" >&3; grep -Eq \"HTTP/1\\\\.[01] (200|301|302)\" <&3'"]
            start_period: 20s
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Asia/Jerusalem
        volumes:
            - /opt/radarr/config:/config
            # Pass the top level folder so that it can do hard links and atomic moves between torrent out and media in
            - storage:/data
        ports:
            - 7878:7878
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.radarr.rule=Host(`radarr.internal.mikeage.net`)
volumes:
    storage:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/storage/temporary/radarr
