---
services:
    homarr:
        image: ghcr.io/ajnart/homarr:0.16.1@sha256:e103abadfb527186af5b4bd43df4eff7c67afa5cd4df8e65fa97910c8840b2a9
        restart: unless-stopped
        environment:
            BASE_URL: https://homarr.internal.mikeage.net
            PASSWORD: ${PASSWORD}
            TZ: Asia/Jerusalem
        volumes:
            - /opt/homarr/configs:/app/data/configs
            - /opt/homarr/icons:/app/public/icons
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 7575:7575
        labels:
            - traefik.enable=true
            - traefik.http.routers.homarr.rule=Host(`homarr.internal.mikeage.net`)
