---
services:
    watchtower:
        image: beatkind/watchtower
        restart: unless-stopped
        hostname: ${HOSTNAME}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WATCHTOWER_POLL_INTERVAL=14400
            - WATCHTOWER_LABEL_ENABLE=true
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@mikeage.net
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=watchtower@mikeage.net
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=outbound.mikeage.net
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=2525
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PASSWORD}
            - WATCHTOWER_WARN_ON_HEAD_FAILURE=never
            - TZ=Asia/Jerusalem
        labels:
            - com.centurylinklabs.watchtower.enable=true
