---
services:
    consul:
        image: hashicorp/consul:1.22.6@sha256:f278b51842bc26129911cccefdfaed52118ae00f692bc42be030d5c66d2370c0
        restart: unless-stopped
        environment:
            - TZ=Asia/Jerusalem
        ports:
            - 8500:8500      # Web UI / API
            - 8600:8600/udp  # DNS (optional)
        volumes:
            - /opt/consul/data:/consul/data
        command: agent -server -bootstrap -ui -client=0.0.0.0
