---
services:
    fr24feed:
        image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest@sha256:da69a8815ce1fa10534e80d785f7b6f2f1df4b51c3b0e4ef29853ca15f0ec968
        restart: unless-stopped
        ports:
            - 8754:8754
        environment:
            TZ: Asia/Jerusalem
            BEASTHOST: ff-2027.lan
            MLAT: no
            FR24KEY: ${KEY}
        tmpfs:
            - /var/log
        labels:
            - traefik.enable=true
            - traefik.http.routers.fr24feed.rule=Host(`fr24feed.internal.mikeage.net`)
