---
services:
    fr24feed:
        image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest@sha256:80e8662be431f9e960094cedeca6841bc02a78346b30d5533b2d38546eecc16c
        restart: unless-stopped
        ports:
            - 8754:8754
        environment:
            TZ: Asia/Jerusalem
            BEASTHOST: ff-2027.lan
            MLAT: no
            FR24KEY: ${KEY}
        tmpfs:
            - /var/log
        labels:
            - traefik.enable=true
            - traefik.http.routers.fr24feed.rule=Host(`fr24feed.internal.mikeage.net`)
