---
services:
    fr24feed:
        image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest@sha256:a809cc66eed21c331e8da9c919f0ae165db8512aba711e8c76a75ec1b7cfc040
        restart: unless-stopped
        ports:
            - 8754:8754
        environment:
            TZ: Asia/Jerusalem
            BEASTHOST: ff-2027.lan
            MLAT: no
            FR24KEY: ${KEY}
        tmpfs:
            - /var/log
        labels:
            - traefik.enable=true
            - traefik.http.routers.fr24feed.rule=Host(`fr24feed.internal.mikeage.net`)
