---
services:
    stacks:
        image: zelest/stacks:latest@sha256:596d02602f80cef566b61b8abd3c1eee2bc6110c1a39b96401704d20cff71667
        stop_signal: SIGTERM
        stop_grace_period: 30s
        ports:
            - 7789:7788
        volumes:
            - stacks-config:/opt/stacks/config
            - /export/storage/permanent/Booksish:/opt/stacks/download
            - stacks-logs:/opt/stacks/logs
        restart: unless-stopped
        environment:
            USERNAME: ${USERNAME}
            PASSWORD: ${PASSWORD}
            # RESET_ADMIN: true
            SOLVERR_URL: http://flaresolverr:8191
            TZ: Asia/Jerusalem
        labels:
            - traefik.enable=true
            - traefik.http.routers.stacks.rule=Host(`stacks.internal.mikeage.net`)

    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
        ports:
            - 8191:8191
        environment:
            - LOG_LEVEL=info
        restart: unless-stopped
        healthcheck:
            test: [CMD, python3, -c, 'import urllib.request; urllib.request.urlopen("http://127.0.0.1:8191/", timeout=5)']
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        volumes:
            - flaresolverr-config:/config
volumes:
    stacks-config:
    stacks-logs:
    flaresolverr-config:
