---
services:
    sonarr:
        image: ghcr.io/cross-seed/cross-seed
        healthcheck:
            test: [CMD, curl, -fsS, http://127.0.0.1:2468/api/ping]
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        user: 1000:1000 # optional but recommended
        environment:
            - TZ=Asia/Jerusalem
        ports:
            - 2468:2468
        volumes:
            - /opt/cross-seed.sonarr/config:/config
            - /export/storage/temporary/sonarr/torrent_downloads:/data/torrent_downloads
        command: daemon
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.cross-seed-sonarr.rule=Host(`cross-seed-sonarr.internal.mikeage.net`)
    radarr:
        image: ghcr.io/cross-seed/cross-seed
        healthcheck:
            test: [CMD, curl, -fsS, http://127.0.0.1:2468/api/ping]
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        user: 1000:1000 # optional but recommended
        environment:
            - TZ=Asia/Jerusalem
        ports:
            - 2469:2468
        volumes:
            - /opt/cross-seed.radarr/config:/config
            - /export/storage/temporary/radarr/torrent_downloads:/data/torrent_downloads
        command: daemon
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.cross-seed-radarr.rule=Host(`cross-seed-radarr.internal.mikeage.net`)
