---
services:
    streamonitor:
        image: ghcr.io/mikeage/streamonitor:latest
        restart: unless-stopped
        environment:
            STRMNTR_PASSWORD: ${PASSWORD}
            STRMNTR_HOST: 0.0.0.0
            STRMNTR_CONFIRM_DEL: MOBILE
            STRMNTR_STATUS_FREQ: '5'
            STRMNTR_LIST_FREQ: '30'
        volumes:
            - /opt/streamonitor/config.json:/app/config.json
            - /export/unreliable/r/downloads/streamonitor:/app/downloads:rw
      # - ./stripchat_mouflon_keys.json:/app/stripchat_mouflon_keys.json
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        labels:
            - traefik.enable=true
            - traefik.http.routers.streamonitor.rule=Host(`streamonitor.internal.mikeage.net`)
        ports:
            - 5005:5000
