---
services:
    bazarr:
        image: lscr.io/linuxserver/bazarr:1.6.0@sha256:a20fb11a440d704a9d61c283aa26462aad33dc63223b173f8d8c77d33e8e9d59
        healthcheck:
            test: [CMD-SHELL, "bash -ec 'exec 3<>/dev/tcp/127.0.0.1/6767; printf \"GET / HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\\
                      n\" >&3; grep -Eq \"HTTP/1\\\\.[01] (200|301|302)\" <&3'"]
            start_period: 20s
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Asia/Jerusalem
        volumes:
            - /opt/bazarr/config:/config
            - storageTV:/data/media/TV
            - storageKidsTV:/data/media/KidsTV
            - storageMovies:/data/media/Movies
            - storageKidsMovies:/data/media/Kids
        ports:
            - 6767:6767
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.bazarr.rule=Host(`bazarr.internal.mikeage.net`)
volumes:
    storageTV:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/unreliable/sonarr/media/TV
    storageKidsTV:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/unreliable/sonarr/media/KidsTV
    storageMovies:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/storage/temporary/radarr/media/Movies
    storageKidsMovies:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/storage/temporary/radarr/media/Kids
