---
services:
    bazarr:
        image: lscr.io/linuxserver/bazarr:1.5.6@sha256:d736df5df0286373a26d34f47aa413cb8aeada74f6338dac372a6d37ba1b3b0d
        healthcheck:
            test: [CMD-SHELL, "bash -ec 'exec 3<>/dev/tcp/127.0.0.1/6767; printf \"GET / HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\\
                      n\" >&3; grep -Eq \"HTTP/1\\\\.[01] (200|301|302)\" <&3'"]
            start_period: 20s
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Asia/Jerusalem
        volumes:
            - /opt/bazarr/config:/config
            - storage:/data
        ports:
            - 6767:6767
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.bazarr.rule=Host(`bazarr.internal.mikeage.net`)
volumes:
    storage:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/storage
