---
services:
    redis:
        image: redis:latest@sha256:39353c6a2f310da333374e1290c91805d15a85def073b5090f58e4ac646d284c  # https://github.com/rspamd/rspamd-docker/blob/main/examples/compose/compose.yaml
        restart: unless-stopped
        healthcheck:
            test: [CMD, redis-cli, ping]
            start_period: 5s
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - redis-data:/data
    rspamd:
        image: rspamd/rspamd:4.1.4@sha256:e870599c970d19593878e3b0ce3ef2a8e29c18ad305d3fda8703e68f434c99d6
        restart: unless-stopped
        healthcheck:
            test: [CMD, rspamadm, control, stat]
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        depends_on:
            redis:
                condition: service_healthy
        ports:
            - 11332:11332
            - 11334:11334
        volumes:
            - /opt/rspamd/etc:/etc/rspamd
            - rspamd-lib:/var/lib/rspamd
        labels:
            - traefik.enable=true
            - traefik.http.routers.rspamd.rule=Host(`rspamd.internal.mikeage.net`)
            - traefik.http.services.rspamd.loadbalancer.server.port=11334

            - traefik.tcp.routers.rspamdmilter.entrypoints=rspamdmilter
            - traefik.tcp.routers.rspamdmilter.rule=HostSNI(`*`)
            - traefik.tcp.routers.rspamdmilter.service=rspamdmilter
            - traefik.tcp.services.rspamdmilter.loadbalancer.server.port=11332

volumes:
    redis-data:
    rspamd-lib:
