---
services:
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
        restart: unless-stopped
        healthcheck:
            test: [CMD, python3, -c, 'import urllib.request; urllib.request.urlopen("http://127.0.0.1:8191/", timeout=5)']
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        environment:
            - LOG_LEVEL=info
            - TZ=Asia/Jerusalem
        ports:
            - 8191:8191
    freshrss:
        image: freshrss/freshrss:latest@sha256:9100f649f5c946f589f54cdb9be7a65996528f48f691ef90eb262a0e06e5a522
        restart: unless-stopped
        healthcheck:
            test: [CMD, php, -r, exit((int)!@file_get_contents("http://127.0.0.1/"));]
            start_period: 20s
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - /opt/freshrss/data:/var/www/FreshRSS/data
            - /opt/freshrss/extensions:/var/www/FreshRSS/extensions
        environment:
            TZ: Asia/Jerusalem
            CRON_MIN: 23,53
            SERVER_DNS: https://freshrss.internal.mikeage.net
            DB_HOST: mariadb
            DB_BASE: ${DB_BASE}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8086:80
        labels:
            - traefik.enable=true
            - traefik.http.routers.freshrss.rule=Host(`freshrss.internal.mikeage.net`)
        post_start:
            - command: chmod g+w /var/www/FreshRSS/p/api
    mariadb:
        image: mariadb:12@sha256:e0236fc6386e7eacd9359e59d0a078bd7aa0d18280d36d13061121bedeaee903
        restart: unless-stopped
        healthcheck:
            test: [CMD-SHELL, mariadb-admin ping -h 127.0.0.1 -u"$$MYSQL_USER" -p"$$MYSQL_PASSWORD" --silent]
            start_period: 20s
            interval: 10s
            timeout: 5s
            retries: 6
        environment:
            - MYSQL_DATABASE=${DB_BASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - TZ=Asia/Jerusalem
        volumes:
            - /opt/freshrss/db:/var/lib/mysql
