---
services:
    traefik-kop:
        image: ghcr.io/jittering/traefik-kop:0.19@sha256:e772673cc437070646229354e55fb1b5b348cf4d7fade5514e3b61c1f3d0b319
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - REDIS_ADDR=redis.lan:6379
            - BIND_IP=${HOSTNAME}
            - REDIS_PASS=${REDIS_PASS}
            - TZ=Asia/Jerusalem
