---
services:
    uptime-kuma:
        environment:
            - TZ=Asia/Jerusalem
        image: louislam/uptime-kuma
        ports:
            - 3001:3001
        volumes:
            - /opt/uptime-kuma/data:/app/data
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.internal.mikeage.net`)
