---
services:
    uptime-kuma:
        environment:
            - TZ=Asia/Jerusalem
        image: louislam/uptime-kuma:2.2.1@sha256:7337368a77873f159435de9ef09567f68c31285ed5f951dec36256c4b267ee44
        ports:
            - 3001:3001
        volumes:
            - /opt/uptime-kuma/data:/app/data
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.internal.mikeage.net`)
