---
services:
    web:
        image: ghcr.io/karakeep-app/karakeep:0.32.0@sha256:64d6a9bbf2d37b5c808cf06b5d87f1f1c7846fdd3844724145a9741aeb06fd31
        restart: unless-stopped
        volumes:
            - /opt/karakeep/data:/data
        ports:
            - 3008:3000
        env_file:
            - .env
        environment:
            MEILI_ADDR: http://meilisearch:7700
            BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
            DATA_DIR: /data
            TZ: Asia/Jerusalem
        labels:
            - traefik.enable=true
            - traefik.http.routers.karakeep.rule=Host(`karakeep.internal.mikeage.net`)
    chrome:
        image: gcr.io/zenika-hub/alpine-chrome:124@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f
        restart: unless-stopped
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:9222/json/version]
            start_period: 10s
            interval: 30s
            timeout: 5s
            retries: 5
        environment:
            - TZ=Asia/Jerusalem
        command:
            - --no-sandbox
            - --disable-gpu
            - --disable-dev-shm-usage
            - --remote-debugging-address=0.0.0.0
            - --remote-debugging-port=9222
            - --hide-scrollbars
    meilisearch:
        image: getmeili/meilisearch:v1.47.0@sha256:4931c0afd68b12d3db4a608268c6785bba26d3f3b43a228eff62ec38d5a47d8d
        restart: unless-stopped
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:7700/health]
            start_period: 10s
            interval: 30s
            timeout: 5s
            retries: 5
        env_file:
            - .env
        environment:
            MEILI_NO_ANALYTICS: 'true'
            MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE: 'true'
            TZ: Asia/Jerusalem
        volumes:
            - /opt/karakeep/mellisearch:/meili_data
