---
services:
    web:
        image: ghcr.io/karakeep-app/karakeep:0.33.2@sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c
        restart: unless-stopped
        volumes:
            - /opt/karakeep/data:/data
        ports:
            - 3008:3000
        env_file:
            - .env
        environment:
            MEILI_ADDR: http://meilisearch:7700
            BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
            DATA_DIR: /data
            TZ: Asia/Jerusalem
        labels:
            - traefik.enable=true
            - traefik.http.routers.karakeep.rule=Host(`karakeep.internal.mikeage.net`)
    chrome:
        image: ghcr.io/karakeep-app/karakeep-chrome:release@sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7
        restart: unless-stopped
        environment:
            - TZ=Asia/Jerusalem
        init: true
        command:
            - --disable-gpu
            - --disable-dev-shm-usage
            - --hide-scrollbars
            - --disable-blink-features=AutomationControlled
            - --window-size=1440,900
    meilisearch:
        image: getmeili/meilisearch:v1.42.1@sha256:e13a16ddc45f66fd065b3416230c2669426cfa8907f4a43f14a9c09a17691fa4
        restart: unless-stopped
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:7700/health]
            start_period: 10s
            interval: 30s
            timeout: 5s
            retries: 5
        env_file:
            - .env
        environment:
            MEILI_NO_ANALYTICS: 'true'
            MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE: 'true'
            TZ: Asia/Jerusalem
        volumes:
            - /opt/karakeep/mellisearch:/meili_data
