---
services:
    autobrr:
        image: ghcr.io/autobrr/autobrr:v1.88.0@sha256:e200008d43fe6cd2d944c9bcf20900cfb8ba8a8e509625bb78ee51910b994005
        restart: unless-stopped
        healthcheck:
            test: [CMD, curl, -fsS, http://127.0.0.1:7474/]
            start_period: 600s
            interval: 30s
            timeout: 5s
            retries: 5
        user: 1000:1000
        environment:
            - TZ=Asia/Jerusalem
        volumes:
            - /opt/autobrr/config:/config
        ports:
            - 7474:7474
        labels:
            - traefik.enable=true
            - traefik.http.routers.autobrr.rule=Host(`autobrr.internal.mikeage.net`)
