---
services:
    autobrr:
        image: ghcr.io/autobrr/autobrr:v1.77.1@sha256:26796bb64ad4cd5956def3e171d485daf7353e952b603f9602d44836e4c9b314
        restart: unless-stopped
        healthcheck:
            test: [CMD, curl, -fsS, http://127.0.0.1:7474/]
            start_period: 20s
            interval: 30s
            timeout: 5s
            retries: 5
        user: 1000:1000
        environment:
            - TZ=Asia/Jerusalem
        volumes:
            - /opt/autobrr/config:/config
        ports:
            - 7474:7474
        labels:
            - traefik.enable=true
            - traefik.http.routers.autobrr.rule=Host(`autobrr.internal.mikeage.net`)
