---
services:
    autobrr:
        image: ghcr.io/autobrr/autobrr:v1.82.0@sha256:b666903f1bba48e380b211da779ffd89f34f8ebfa2f32b1c4b1e60f8882df2bf
        restart: unless-stopped
        healthcheck:
            test: [CMD, curl, -fsS, http://127.0.0.1:7474/]
            start_period: 600s
            interval: 30s
            timeout: 5s
            retries: 5
        user: 1000:1000
        environment:
            - TZ=Asia/Jerusalem
        volumes:
            - /opt/autobrr/config:/config
        ports:
            - 7474:7474
        labels:
            - traefik.enable=true
            - traefik.http.routers.autobrr.rule=Host(`autobrr.internal.mikeage.net`)
