---
services:
    transmission:
        image: lscr.io/linuxserver/transmission:4.1.1@sha256:dd888c17f97eca1a2dda4aa7986c9080fe1b69a61aef845440f1bd9285aa3708
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Jerusalem
            # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
            - USER=admin  # optional
            - PASS=***REMOVED***  # optional
            # - WHITELIST=iplist #optional
            # - PEERPORT=peerport #optional
            # - HOST_WHITELIST=dnsname list #optional
        volumes:
            - /opt/transmission/config:/config
            - torrent_downloads:/data/torrent_downloads
            # - /path/to/watch/folder:/watch
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
volumes:
    torrent_downloads:
        driver: local
        driver_opts:
            type: nfs
            o: addr=openmediavault.lan,nfsvers=4.2,soft,timeo=600,retrans=2,rsize=1048576,wsize=1048576
            device: :/storage/torrent_downloads
