---
services:
    ctbrec-alpine:
        image: jafea7/ctbrec-alpine:26.5.20@sha256:aa30a099df9e83d9502d8e3aca4c7dd2693f54be771b8357e64429e7fdedb8a7
        restart: unless-stopped
        environment:
            - TZ=Asia/Jerusalem
            - PGID=1000
            - PUID=1000
        ports:
            - 18443:8443
        volumes:
            - ctbrec-config:/app/config:rw
            - /export/unreliable/r/downloads/ctbrec:/app/media:rw
        labels:
            - traefik.enable=true
            - traefik.http.routers.ctbrec.rule=Host(`ctbrec.internal.mikeage.net`)
            - traefik.http.routers.ctbrec.middlewares=basic-auth@file
            - traefik.http.services.ctbrec.loadbalancer.server.scheme=https
            - traefik.http.services.ctbrec.loadbalancer.serverstransport=insecure-skip-verify@file
volumes:
    ctbrec-config:
