---
services:
    qui:
        image: ghcr.io/autobrr/qui:v1.21.0@sha256:79c1b800297c985cbeb7fb3215cbb00b32a22cb6a39b7e356eb8bb75d872c924
        restart: unless-stopped
        ports:
            - 7476:7476
        volumes:
            - /opt/qui/config:/config
        labels:
            - traefik.enable=true
            - traefik.http.routers.qui.rule=Host(`qui.internal.mikeage.net`)
