---
services:
    qui:
        image: ghcr.io/autobrr/qui:v1.28.0@sha256:0bfe512eca0ec2ad639927f46a1a2a914feb75492d8032b7f866025162f562d5
        restart: unless-stopped
        ports:
            - 7476:7476
        volumes:
            - /opt/qui/config:/config
        labels:
            - traefik.enable=true
            - traefik.http.routers.qui.rule=Host(`qui.internal.mikeage.net`)
