---
services:
    qui:
        image: ghcr.io/autobrr/qui:v1.16.1@sha256:07b6ea9572e52e8b5f70f8fb15a7c688d8d754a7616242d3ad0b21dbd5c05836
        restart: unless-stopped
        ports:
            - 7476:7476
        volumes:
            - /opt/qui/config:/config
        labels:
            - traefik.enable=true
            - traefik.http.routers.qui.rule=Host(`qui.internal.mikeage.net`)
