---
services:
    autoheal:
        image: willfarrell/autoheal:latest@sha256:70a53a52f9261e81bb81c1be7be3248541fcb6836ef0753c0c10faf5c811971a
        network_mode: none
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
        restart: unless-stopped
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
