---
services:
    autoheal:
        image: willfarrell/autoheal:latest@sha256:f60b4441b32aa297ae5bd3ce8419dc2b28e02646909ab1917b39fbf41206008c
        network_mode: none
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
        restart: unless-stopped
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
