---
services:
    autoheal:
        image: willfarrell/autoheal:latest@sha256:051fd8b57859112ecc6596c4017c36755c401fab2b928dabe2cf86c97ea2f707
        network_mode: none
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
        restart: unless-stopped
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
