---
name: Renovate

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

on:
    push:
        branches:
            - main
    issue_comment:
        types:
            - created
    issues:
        types:
            - edited
    pull_request:
        types:
            - edited
            - closed
    workflow_dispatch:
    schedule:
        - cron: 2/15 * * * *

permissions:
    contents: read

jobs:
    renovate:
        if: >-
            github.event_name == 'workflow_dispatch' ||
            github.event_name == 'schedule' ||
            github.event_name == 'push' ||
            (
                github.event_name == 'issue_comment' &&
                github.event.action == 'created' &&
                contains(github.event.comment.body, '@renovate')
            ) ||
            (
                github.event_name == 'issues' &&
                github.event.action == 'edited' &&
                github.event.issue.title == 'Dependency Dashboard'
            ) ||
            (
                github.event_name == 'pull_request' &&
                (
                    github.event.action == 'edited' ||
                    github.event.action == 'closed'
                ) &&
                startsWith(github.event.pull_request.head.ref, 'renovate/')
            )
        runs-on: ubuntu-latest
        env:
            LOG_LEVEL: info
            RENOVATE_REPOSITORIES: ${{ github.repository }}

        steps:
            - name: Check out repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Run Renovate
              uses: renovatebot/github-action@b50d2ba2bd928235abdcc14d06dfafc217f1c565 # v46.1.18
              with:
                  configurationFile: .github/renovate-bot.json
                  token: ${{ secrets.RENOVATE_TOKEN }}
